
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.93
blur = true
decorations = "Buttonless"

[window.dimensions]
columns = 130
lines = 40

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16

[general]
import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

#enabled = true
#for video
# size = 35.0
